import { Inter, Open_Sans, Staatliches } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header";

const staatliches = Staatliches({
	subsets: ["latin"],
	weight: ["400"],
	variable: "--font-staat",
});
const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});

const open_sans = Open_Sans({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-open-sans",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${inter.variable} ${open_sans.variable} ${staatliches.variable} antialiased`}
			>
				<Navbar />

				{children}
			</body>
		</html>
	);
}
